version: 2

formats:
  - epub
  - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - graphviz

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
